# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AviationLatLonCalc
                                 A QGIS plugin
 Plugin to calculate latitude and longitude when loacitons given in aviation lake way (azimuth, bearings, offesets against reference point)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-16
        copyright            : (C) 2019 by Paweł Strzelewicz
        email                : aviationgisapp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AviationLatLonCalc class from file AviationLatLonCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aviation_latlon_calc import AviationLatLonCalc
    return AviationLatLonCalc(iface)
